### ISSUE TITLE
freeze on "Loading..." (and cant download newer versions (says its malware?))

### ISSUE THREAD

**Issue by Someone2124** [Wieku/danser-go#357]
basically Danser will work normally and let me choose maps to watch and or record or screen shot and same with importing replays and all that, the main problem is it freezes every single time i wanna watch a replay or have a map for it do dance or even try to play standard

[danser.log](https://github.com/Wieku/danser-go/files/14229027/danser.log)

https://github.com/Wieku/danser-go/assets/40772709/49b5b985-c278-4557-8b40-24a7a39741fa

**Comment by FeldWay35** [comment]
just downgrade the version to 0.8.2, don't use the new version

**Comment by Wieku** [comment]
@FeldWay35 Please don't make such suggestions. Issue should be solved, not swept under the rug.

@Someone2124 does the same issue happen on newest version? Can you share the settings?

**Comment by Slingexe** [comment]
What AV is marking the newer version of Danser as Malware?

**Comment by Someone2124** [comment]
@Wieku dude i completely forgot about this, my fault-
(i make album 👍)

its prolly something with my settings but yeah it still happens with the new version, all though im using my custom JSON settings and when i used the default ones it worked fine but still freezes on mine

yea lemme share my JSON settings 
[Zeas Custom Danser Preset.json](https://github.com/user-attachments/files/16154744/Zeas.Custom.Danser.Preset.json)

**Comment by Someone2124** [comment]
@Wieku dude i completely forgot about this, my fault-
(i make album 👍)

its prolly something with my settings but yeah it still happens with the new version, all though im using my custom JSON settings and when i used the default ones it worked fine but still freezes on mine

yea lemme share my JSON settings
[Zeas Custom Danser Preset.json](https://github.com/user-attachments/files/16154757/Zeas.Custom.Danser.Preset.json)

**Comment by Someone2124** [comment]
> Can you share the settings?

windows defender ._.

**Comment by Someone2124** [comment]
,l,l

**Comment by Wieku** [comment]
@Someone2124 ugh, sorry for not responding sooner. Your settings work on my PC. Can you try the same settings but setting MSAA to 8x instead of 16x?

**Comment by Wieku** [comment]
Closing as stale
